name: scalafmt

env:
  SBT_VERSION: 1.10.11

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: ${{ env.SBT_VERSION }}

      - name: Format coode
        run: |
          sbt scalafmtSbtCheck scalafmtCheck
